
import java.awt.Color;
import java.awt.Cursor;

/*
 * NewJFrame1.java
 *
 * Created on 1 יוני 2008, 21:16
 */
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;



/**
 *
 * @author  User
 */
public class MainFrame extends GeneralJFrame1 {
    
    /** Creates new form NewJFrame1 */
    public MainFrame() {
        setFrameAtCenter(getWidth(), getHeight());
	initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelPicture8 = new javax.swing.JLabel();
        jLabelPicture9 = new javax.swing.JLabel();
        jLabelPicture10 = new javax.swing.JLabel();
        jLabelPicture11 = new javax.swing.JLabel();
        jLabelPicture12 = new javax.swing.JLabel();
        jLabelPicture13 = new javax.swing.JLabel();
        jLabelPicture14 = new javax.swing.JLabel();
        jLabelPermission2 = new javax.swing.JLabel();
        jLabelMovie3 = new javax.swing.JLabel();
        jLabelMovie2 = new javax.swing.JLabel();
        jLabelMovie5 = new javax.swing.JLabel();
        jLabelMovie1 = new javax.swing.JLabel();
        jLabelMovie4 = new javax.swing.JLabel();
        jLabelMovie6 = new javax.swing.JLabel();
        jLabelMovie7 = new javax.swing.JLabel();
        jLabelRate7 = new javax.swing.JLabel();
        jLabelRate3 = new javax.swing.JLabel();
        jLabelRate5 = new javax.swing.JLabel();
        jLabelRate2 = new javax.swing.JLabel();
        jLabelRate1 = new javax.swing.JLabel();
        jLabelRate4 = new javax.swing.JLabel();
        jLabelRate6 = new javax.swing.JLabel();
        jLabelHello = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelPermission = new javax.swing.JLabel();
        jLabelPermission1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabelPermission3 = new javax.swing.JLabel();
        jLabelRate12 = new javax.swing.JLabel();
        jLabelRate8 = new javax.swing.JLabel();
        jLabelRate9 = new javax.swing.JLabel();
        jLabelPicture21 = new javax.swing.JLabel();
        jLabelRate14 = new javax.swing.JLabel();
        jLabelPicture20 = new javax.swing.JLabel();
        jLabelMovie8 = new javax.swing.JLabel();
        jLabelMovie13 = new javax.swing.JLabel();
        jLabelMovie12 = new javax.swing.JLabel();
        jLabelMovie11 = new javax.swing.JLabel();
        jLabelRate13 = new javax.swing.JLabel();
        jLabelPicture17 = new javax.swing.JLabel();
        jLabelRate11 = new javax.swing.JLabel();
        jLabelPicture16 = new javax.swing.JLabel();
        jLabelPicture18 = new javax.swing.JLabel();
        jLabelMovie9 = new javax.swing.JLabel();
        jLabelMovie10 = new javax.swing.JLabel();
        jLabelRate10 = new javax.swing.JLabel();
        jLabelPicture15 = new javax.swing.JLabel();
        jLabelPicture19 = new javax.swing.JLabel();
        jLabelMovie14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel2.setBackground(backgroundColor);
        jPanel2.setForeground(new java.awt.Color(212, 208, 200));

        jPanel1.setBackground(backgroundColor);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setForeground(headersFontColor);

        jPanel3.setBackground(backgroundColor);
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPicture8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelPicture9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelPicture10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelPicture11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelPicture12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelPicture13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelPicture14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelPermission2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelPermission2.setForeground(headersFontColor);
        jLabelPermission2.setText("New Movies");

        jLabelMovie3.setForeground(regularFontColor);
        jLabelMovie3.setText("Shrek1");

        jLabelMovie2.setForeground(regularFontColor);
        jLabelMovie2.setText("Shrek1");

        jLabelMovie5.setForeground(regularFontColor);
        jLabelMovie5.setText("Shrek1");

        jLabelMovie1.setForeground(regularFontColor);
        jLabelMovie1.setText("Shrek1");

        jLabelMovie4.setForeground(regularFontColor);
        jLabelMovie4.setText("Shrek1");

        jLabelMovie6.setForeground(regularFontColor);
        jLabelMovie6.setText("Shrek1");

        jLabelMovie7.setForeground(regularFontColor);
        jLabelMovie7.setText("Shrek1");

        jLabelRate7.setForeground(regularFontColor);
        jLabelRate7.setText("1");

        jLabelRate3.setForeground(regularFontColor);
        jLabelRate3.setText("1");

        jLabelRate5.setForeground(regularFontColor);
        jLabelRate5.setText("1");

        jLabelRate2.setForeground(regularFontColor);
        jLabelRate2.setText("1");

        jLabelRate1.setForeground(regularFontColor);
        jLabelRate1.setText("1");

        jLabelRate4.setForeground(regularFontColor);
        jLabelRate4.setText("1");

        jLabelRate6.setForeground(regularFontColor);
        jLabelRate6.setText("1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelPicture8)
                        .addComponent(jLabelPicture9)
                        .addComponent(jLabelPicture10)
                        .addComponent(jLabelPicture11)
                        .addComponent(jLabelPicture12)
                        .addComponent(jLabelPicture13)
                        .addComponent(jLabelPicture14)
                        .addComponent(jLabelPermission2))
                    .addGap(28, 28, 28)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelMovie3)
                        .addComponent(jLabelMovie2)
                        .addComponent(jLabelMovie5)
                        .addComponent(jLabelMovie1)
                        .addComponent(jLabelMovie4)
                        .addComponent(jLabelMovie6)
                        .addComponent(jLabelMovie7))
                    .addGap(46, 46, 46)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelRate7)
                        .addComponent(jLabelRate3)
                        .addComponent(jLabelRate5)
                        .addComponent(jLabelRate2)
                        .addComponent(jLabelRate1)
                        .addComponent(jLabelRate4)
                        .addComponent(jLabelRate6))
                    .addContainerGap(103, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabelPermission2)
                            .addGap(18, 18, 18)
                            .addComponent(jLabelPicture14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelPicture13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelPicture12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelPicture11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelPicture10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelPicture9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelPicture8))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabelMovie1)
                                    .addGap(47, 47, 47)
                                    .addComponent(jLabelMovie2)
                                    .addGap(43, 43, 43)
                                    .addComponent(jLabelMovie3)
                                    .addGap(44, 44, 44)
                                    .addComponent(jLabelMovie4)
                                    .addGap(46, 46, 46)
                                    .addComponent(jLabelMovie5)
                                    .addGap(42, 42, 42)
                                    .addComponent(jLabelMovie6)
                                    .addGap(46, 46, 46)
                                    .addComponent(jLabelMovie7))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabelRate1)
                                    .addGap(47, 47, 47)
                                    .addComponent(jLabelRate2)
                                    .addGap(43, 43, 43)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelRate7, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabelRate3)
                                            .addGap(44, 44, 44)
                                            .addComponent(jLabelRate4)
                                            .addGap(46, 46, 46)
                                            .addComponent(jLabelRate5)
                                            .addGap(42, 42, 42)
                                            .addComponent(jLabelRate6)
                                            .addGap(60, 60, 60)))))))
                    .addContainerGap(37, Short.MAX_VALUE)))
        );

        jLabelHello.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelHello.setForeground(headersFontColor);
        jLabelHello.setText("Hello");

        jLabelUserName.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelUserName.setForeground(headersFontColor);
        jLabelUserName.setText("Israel Israeli");

        jLabelPermission.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelPermission.setForeground(headersFontColor);
        jLabelPermission.setText("Permission Mode");

        jLabelPermission1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelPermission1.setForeground(headersFontColor);
        jLabelPermission1.setText("Log Out");
        jLabelPermission1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPermission1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelPermission1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPermission1MouseExited(evt);
            }
        });

        jPanel4.setBackground(backgroundColor);
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPermission3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelPermission3.setForeground(headersFontColor);
        jLabelPermission3.setText("Most Recommended Movies");

        jLabelRate12.setForeground(regularFontColor);
        jLabelRate12.setText("1");

        jLabelRate8.setForeground(regularFontColor);
        jLabelRate8.setText("1");

        jLabelRate9.setForeground(regularFontColor);
        jLabelRate9.setText("1");

        jLabelPicture21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelRate14.setForeground(regularFontColor);
        jLabelRate14.setText("1");

        jLabelPicture20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelMovie8.setForeground(regularFontColor);
        jLabelMovie8.setText("Shrek1");

        jLabelMovie13.setForeground(regularFontColor);
        jLabelMovie13.setText("Shrek1");

        jLabelMovie12.setForeground(regularFontColor);
        jLabelMovie12.setText("Shrek1");

        jLabelMovie11.setForeground(regularFontColor);
        jLabelMovie11.setText("Shrek1");

        jLabelRate13.setForeground(regularFontColor);
        jLabelRate13.setText("1");

        jLabelPicture17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelRate11.setForeground(regularFontColor);
        jLabelRate11.setText("1");

        jLabelPicture16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelPicture18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelMovie9.setForeground(regularFontColor);
        jLabelMovie9.setText("Shrek1");

        jLabelMovie10.setForeground(regularFontColor);
        jLabelMovie10.setText("Shrek1");

        jLabelRate10.setForeground(regularFontColor);
        jLabelRate10.setText("1");

        jLabelPicture15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelPicture19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelMovie14.setForeground(regularFontColor);
        jLabelMovie14.setText("Shrek1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPermission3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPicture15)
                            .addComponent(jLabelPicture16)
                            .addComponent(jLabelPicture17)
                            .addComponent(jLabelPicture18)
                            .addComponent(jLabelPicture19)
                            .addComponent(jLabelPicture20)
                            .addComponent(jLabelPicture21))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMovie8)
                            .addComponent(jLabelMovie9)
                            .addComponent(jLabelMovie10)
                            .addComponent(jLabelMovie11)
                            .addComponent(jLabelMovie12)
                            .addComponent(jLabelMovie13)
                            .addComponent(jLabelMovie14))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRate8)
                            .addComponent(jLabelRate9)
                            .addComponent(jLabelRate10)
                            .addComponent(jLabelRate11)
                            .addComponent(jLabelRate12)
                            .addComponent(jLabelRate13)
                            .addComponent(jLabelRate14))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPermission3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPicture21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPicture20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPicture19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPicture18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPicture17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPicture16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPicture15))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelMovie11)
                                .addGap(47, 47, 47)
                                .addComponent(jLabelMovie9)
                                .addGap(43, 43, 43)
                                .addComponent(jLabelMovie8)
                                .addGap(44, 44, 44)
                                .addComponent(jLabelMovie12)
                                .addGap(46, 46, 46)
                                .addComponent(jLabelMovie10)
                                .addGap(42, 42, 42)
                                .addComponent(jLabelMovie13)
                                .addGap(46, 46, 46)
                                .addComponent(jLabelMovie14))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelRate12)
                                .addGap(47, 47, 47)
                                .addComponent(jLabelRate11)
                                .addGap(43, 43, 43)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelRate8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabelRate9)
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabelRate13)
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabelRate10)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabelRate14)
                                        .addGap(60, 60, 60)))))))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setText("Rate Movies");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("System Management");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Settings");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setForeground(headerColor);
        jLabel1.setText("Recommendation Movies System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelHello)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelUserName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                                .addComponent(jLabelPermission)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPermission1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(164, 164, 164))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 316, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 317, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelHello)
                        .addComponent(jLabelUserName)
                        .addComponent(jLabelPermission1)
                        .addComponent(jLabelPermission))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 321, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 321, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    new RateMovies().setVisible(true);
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    new SystemManagement().setVisible(true);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    new Settings(this).setVisible(true);
}//GEN-LAST:event_jButton3ActionPerformed

private void jLabelPermission1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPermission1MouseClicked
    System.exit(1);// TODO add your handling code here:
}//GEN-LAST:event_jLabelPermission1MouseClicked

private void jLabelPermission1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPermission1MouseEntered
    setLinkEntered(jLabelPermission1, linkHeaderColor);// TODO add your handling code here:
}//GEN-LAST:event_jLabelPermission1MouseEntered

private void jLabelPermission1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPermission1MouseExited
    setLinkExited(jLabelPermission1, this.headersFontColor);// TODO add your handling code here:
}//GEN-LAST:event_jLabelPermission1MouseExited
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelHello;
    private javax.swing.JLabel jLabelMovie1;
    private javax.swing.JLabel jLabelMovie10;
    private javax.swing.JLabel jLabelMovie11;
    private javax.swing.JLabel jLabelMovie12;
    private javax.swing.JLabel jLabelMovie13;
    private javax.swing.JLabel jLabelMovie14;
    private javax.swing.JLabel jLabelMovie2;
    private javax.swing.JLabel jLabelMovie3;
    private javax.swing.JLabel jLabelMovie4;
    private javax.swing.JLabel jLabelMovie5;
    private javax.swing.JLabel jLabelMovie6;
    private javax.swing.JLabel jLabelMovie7;
    private javax.swing.JLabel jLabelMovie8;
    private javax.swing.JLabel jLabelMovie9;
    private javax.swing.JLabel jLabelPermission;
    private javax.swing.JLabel jLabelPermission1;
    private javax.swing.JLabel jLabelPermission2;
    private javax.swing.JLabel jLabelPermission3;
    private javax.swing.JLabel jLabelPicture10;
    private javax.swing.JLabel jLabelPicture11;
    private javax.swing.JLabel jLabelPicture12;
    private javax.swing.JLabel jLabelPicture13;
    private javax.swing.JLabel jLabelPicture14;
    private javax.swing.JLabel jLabelPicture15;
    private javax.swing.JLabel jLabelPicture16;
    private javax.swing.JLabel jLabelPicture17;
    private javax.swing.JLabel jLabelPicture18;
    private javax.swing.JLabel jLabelPicture19;
    private javax.swing.JLabel jLabelPicture20;
    private javax.swing.JLabel jLabelPicture21;
    private javax.swing.JLabel jLabelPicture8;
    private javax.swing.JLabel jLabelPicture9;
    private javax.swing.JLabel jLabelRate1;
    private javax.swing.JLabel jLabelRate10;
    private javax.swing.JLabel jLabelRate11;
    private javax.swing.JLabel jLabelRate12;
    private javax.swing.JLabel jLabelRate13;
    private javax.swing.JLabel jLabelRate14;
    private javax.swing.JLabel jLabelRate2;
    private javax.swing.JLabel jLabelRate3;
    private javax.swing.JLabel jLabelRate4;
    private javax.swing.JLabel jLabelRate5;
    private javax.swing.JLabel jLabelRate6;
    private javax.swing.JLabel jLabelRate7;
    private javax.swing.JLabel jLabelRate8;
    private javax.swing.JLabel jLabelRate9;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
    //private Color backgroundColor = Color.DARK_GRAY;
    //private Color headerColor = new Color(255,51,51);
    //private Color regularFontColor = Color.LIGHT_GRAY;
    //private Color headersFontColor = Color.WHITE;

    public javax.swing.JPanel getJPanel1() {
        return jPanel1;
    }

    public javax.swing.JPanel getJPanel2() {
        return jPanel2;
    }

    public javax.swing.JPanel getJPanel3() {
        return jPanel3;
    }

    public javax.swing.JPanel getJPanel4() {
        return jPanel4;
    }
    
}
