package gui;

import domain.Movie;
import domain.controller.Controller;
import java.util.Vector;
public class MainFrame extends GeneralJFrame {
    
    private Controller _controller;
    private Vector[] _rated;
    
    /** Creates new form NewJFrame1 */
    public MainFrame(Controller controller) {
        this._controller = controller;
        setFrameAtCenter(this.getWidth(), this.getHeight());
	initComponents();
        setMostRecommendedMovies();
    }
    
    private void setMostRecommendedMovies(){
         _rated = _controller.get_Strategy().get10Recomendations(_controller.getCurrentUser().getId());
         Vector<Movie> movies = _rated[0];
         Vector<Integer> rates = _rated[1];

         if (movies.size() > 0){
             this.jLabelMovie1.setText(movies.elementAt(0).get_name());
             this.jLabelRate1.setText(rates.elementAt(0).toString());
         }
         if (movies.size() > 1){
             this.jLabelMovie2.setText(movies.elementAt(1).get_name());
             this.jLabelRate2.setText(rates.elementAt(1).toString());
         }
         if (movies.size() > 2){
             this.jLabelMovie3.setText(movies.elementAt(2).get_name());
             this.jLabelRate3.setText(rates.elementAt(2).toString());
         }
         if (movies.size() > 3){
             this.jLabelMovie4.setText(movies.elementAt(3).get_name());
             this.jLabelRate4.setText(rates.elementAt(3).toString());
         }
         if (movies.size() > 4){
             this.jLabelMovie5.setText(movies.elementAt(4).get_name());
             this.jLabelRate5.setText(rates.elementAt(4).toString());
         }
         if (movies.size() > 5){
             this.jLabelMovie6.setText(movies.elementAt(5).get_name());
             this.jLabelRate6.setText(rates.elementAt(5).toString());
         }
         if (movies.size() > 6){
             this.jLabelMovie7.setText(movies.elementAt(6).get_name());
             this.jLabelRate7.setText(rates.elementAt(6).toString());
         }
         if (movies.size() > 7){
             this.jLabelMovie8.setText(movies.elementAt(7).get_name());
             this.jLabelRate8.setText(rates.elementAt(7).toString());
         }if (movies.size() > 8){
             this.jLabelMovie9.setText(movies.elementAt(8).get_name());
             this.jLabelRate9.setText(rates.elementAt(8).toString());
         }
         if (movies.size() > 9){
             this.jLabelMovie10.setText(movies.elementAt(9).get_name());
             this.jLabelRate10.setText(rates.elementAt(9).toString());
         }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelHello = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelPermissionMode = new javax.swing.JLabel();
        jLabelLogOut = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabelPermission3 = new javax.swing.JLabel();
        jLabelRate1 = new javax.swing.JLabel();
        jLabelRate3 = new javax.swing.JLabel();
        jLabelPicture1 = new javax.swing.JLabel();
        jLabelPicture2 = new javax.swing.JLabel();
        jLabelMovie3 = new javax.swing.JLabel();
        jLabelMovie4 = new javax.swing.JLabel();
        jLabelMovie1 = new javax.swing.JLabel();
        jLabelRate4 = new javax.swing.JLabel();
        jLabelPicture5 = new javax.swing.JLabel();
        jLabelRate2 = new javax.swing.JLabel();
        jLabelPicture4 = new javax.swing.JLabel();
        jLabelMovie2 = new javax.swing.JLabel();
        jLabelMovie5 = new javax.swing.JLabel();
        jLabelRate5 = new javax.swing.JLabel();
        jLabelPicture3 = new javax.swing.JLabel();
        jLabelPicture10 = new javax.swing.JLabel();
        jLabelPicture9 = new javax.swing.JLabel();
        jLabelPicture8 = new javax.swing.JLabel();
        jLabelPicture7 = new javax.swing.JLabel();
        jLabelPicture6 = new javax.swing.JLabel();
        jLabelMovie8 = new javax.swing.JLabel();
        jLabelMovie7 = new javax.swing.JLabel();
        jLabelMovie10 = new javax.swing.JLabel();
        jLabelMovie6 = new javax.swing.JLabel();
        jLabelMovie9 = new javax.swing.JLabel();
        jLabelRate8 = new javax.swing.JLabel();
        jLabelRate10 = new javax.swing.JLabel();
        jLabelRate7 = new javax.swing.JLabel();
        jLabelRate6 = new javax.swing.JLabel();
        jLabelRate9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonRateMovies = new javax.swing.JButton();
        jButtonSystemManagement = new javax.swing.JButton();
        jButtonSettings = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel2.setBackground(backgroundColor);
        jPanel2.setForeground(new java.awt.Color(212, 208, 200));

        jPanel1.setBackground(backgroundColor);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setForeground(headersFontColor);

        jLabelHello.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelHello.setForeground(headersFontColor);
        jLabelHello.setText("Hello");

        jLabelUserName.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelUserName.setForeground(headersFontColor);
        jLabelUserName.setText(_controller.getCurrentUser().getName());

        jLabelPermissionMode.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelPermissionMode.setForeground(headersFontColor);
        jLabelPermissionMode.setText(_controller.getCurrentUser().getPermission().toLowerCase());

        jLabelLogOut.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelLogOut.setForeground(headersFontColor);
        jLabelLogOut.setText("Log Out");
        jLabelLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLogOutMouseExited(evt);
            }
        });

        jPanel4.setBackground(backgroundColor);
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPermission3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelPermission3.setForeground(headersFontColor);
        jLabelPermission3.setText("Most Recommended Movies");

        jLabelRate1.setForeground(regularFontColor);
        jLabelRate1.setText("--");

        jLabelRate3.setForeground(regularFontColor);
        jLabelRate3.setText("--");

        jLabelPicture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelPicture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelMovie3.setForeground(regularFontColor);
        jLabelMovie3.setText("-------");

        jLabelMovie4.setForeground(regularFontColor);
        jLabelMovie4.setText("-------");

        jLabelMovie1.setForeground(regularFontColor);
        jLabelMovie1.setText("-------");

        jLabelRate4.setForeground(regularFontColor);
        jLabelRate4.setText("--");

        jLabelPicture5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelRate2.setForeground(regularFontColor);
        jLabelRate2.setText("--");

        jLabelPicture4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelMovie2.setForeground(regularFontColor);
        jLabelMovie2.setText("-------");

        jLabelMovie5.setForeground(regularFontColor);
        jLabelMovie5.setText("-------");

        jLabelRate5.setForeground(regularFontColor);
        jLabelRate5.setText("--");

        jLabelPicture3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelPicture10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelPicture9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelPicture8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelPicture7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelPicture6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelMovie8.setForeground(regularFontColor);
        jLabelMovie8.setText("-------");

        jLabelMovie7.setForeground(regularFontColor);
        jLabelMovie7.setText("-------");

        jLabelMovie10.setForeground(regularFontColor);
        jLabelMovie10.setText("-------");

        jLabelMovie6.setForeground(regularFontColor);
        jLabelMovie6.setText("-------");

        jLabelMovie9.setForeground(regularFontColor);
        jLabelMovie9.setText("-------");

        jLabelRate8.setForeground(regularFontColor);
        jLabelRate8.setText("--");

        jLabelRate10.setForeground(regularFontColor);
        jLabelRate10.setText("--");

        jLabelRate7.setForeground(regularFontColor);
        jLabelRate7.setText("--");

        jLabelRate6.setForeground(regularFontColor);
        jLabelRate6.setText("--");

        jLabelRate9.setForeground(regularFontColor);
        jLabelRate9.setText("--");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelPicture5)
                            .add(jLabelPicture4)
                            .add(jLabelPicture3)
                            .add(jLabelPicture2)
                            .add(jLabelPicture1))
                        .add(43, 43, 43)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelMovie2)
                            .add(jLabelMovie5)
                            .add(jLabelMovie4)
                            .add(jLabelMovie3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabelMovie1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(27, 27, 27)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelRate3)
                            .add(jLabelRate5)
                            .add(jLabelRate2)
                            .add(jLabelRate1)
                            .add(jLabelRate4))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 196, Short.MAX_VALUE)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelPicture9)
                            .add(jLabelPicture8)
                            .add(jLabelPicture7)
                            .add(jLabelPicture6)
                            .add(jLabelPicture10))
                        .add(43, 43, 43)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelMovie8)
                            .add(jLabelMovie7)
                            .add(jLabelMovie10)
                            .add(jLabelMovie6)
                            .add(jLabelMovie9))
                        .add(46, 46, 46)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelRate8)
                            .add(jLabelRate10)
                            .add(jLabelRate7)
                            .add(jLabelRate6)
                            .add(jLabelRate9))
                        .add(20, 20, 20))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jLabelPermission3)
                        .addContainerGap(620, Short.MAX_VALUE))))
        );

        jPanel4Layout.linkSize(new java.awt.Component[] {jLabelMovie1, jLabelMovie2, jLabelMovie3, jLabelMovie4, jLabelMovie5, jLabelMovie6}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelPermission3)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jLabelPicture6)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabelPicture7)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabelPicture8)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabelPicture9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabelPicture10))
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(20, 20, 20)
                                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jPanel4Layout.createSequentialGroup()
                                        .add(jLabelMovie6)
                                        .add(47, 47, 47)
                                        .add(jLabelMovie7)
                                        .add(43, 43, 43)
                                        .add(jLabelMovie8)
                                        .add(44, 44, 44)
                                        .add(jLabelMovie9)
                                        .add(46, 46, 46)
                                        .add(jLabelMovie10))
                                    .add(jPanel4Layout.createSequentialGroup()
                                        .add(jLabelRate6)
                                        .add(47, 47, 47)
                                        .add(jLabelRate7)
                                        .add(43, 43, 43)
                                        .add(jLabelRate8)
                                        .add(44, 44, 44)
                                        .add(jLabelRate9)
                                        .add(46, 46, 46)
                                        .add(jLabelRate10))))
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jLabelPicture1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabelPicture2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabelPicture3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabelPicture4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabelPicture5))))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(38, 38, 38)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jLabelRate1)
                                .add(47, 47, 47)
                                .add(jLabelRate2)
                                .add(43, 43, 43)
                                .add(jLabelRate3)
                                .add(44, 44, 44)
                                .add(jLabelRate4)
                                .add(46, 46, 46)
                                .add(jLabelRate5))
                            .add(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabelMovie1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabelMovie2)
                                .add(43, 43, 43)
                                .add(jLabelMovie3)
                                .add(44, 44, 44)
                                .add(jLabelMovie4)
                                .add(46, 46, 46)
                                .add(jLabelMovie5)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButtonRateMovies.setText("Rate Movies");
        jButtonRateMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRateMoviesActionPerformed(evt);
            }
        });

        jButtonSystemManagement.setText("System Management");
        jButtonSystemManagement.setEnabled(_controller.getCurrentUser().getPermission().equalsIgnoreCase("Administrator"));
        jButtonSystemManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSystemManagementActionPerformed(evt);
            }
        });

        jButtonSettings.setText("Settings");
        jButtonSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setForeground(headerColor);
        jLabel1.setText("Recommendation Movies System");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jButtonRateMovies)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonSettings)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonSystemManagement))
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jSeparator1)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabelHello)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelUserName)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabelPermissionMode)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelLogOut)))
                .addContainerGap())
            .add(jPanel1Layout.createSequentialGroup()
                .add(257, 257, 257)
                .add(jLabel1)
                .addContainerGap(260, Short.MAX_VALUE))
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel1Layout.createSequentialGroup()
                    .add(0, 407, Short.MAX_VALUE)
                    .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 406, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabelHello)
                        .add(jLabelUserName))
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabelLogOut)
                        .add(jLabelPermissionMode))
                    .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1)
                .add(11, 11, 11)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonRateMovies)
                    .add(jButtonSettings)
                    .add(jButtonSystemManagement))
                .add(14, 14, 14))
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel1Layout.createSequentialGroup()
                    .add(0, 241, Short.MAX_VALUE)
                    .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 241, Short.MAX_VALUE)))
        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 496, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonRateMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRateMoviesActionPerformed
    this.setEnabled(false);
    new RateMovies(this, _controller).setVisible(true);
}//GEN-LAST:event_jButtonRateMoviesActionPerformed

private void jButtonSystemManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSystemManagementActionPerformed
    new SystemManagement(_controller).setVisible(true);
}//GEN-LAST:event_jButtonSystemManagementActionPerformed

private void jButtonSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettingsActionPerformed
    new Settings(this, _controller).setVisible(true);
}//GEN-LAST:event_jButtonSettingsActionPerformed

private void jLabelLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogOutMouseClicked
    _controller.shutDown();
    System.exit(1);// TODO add your handling code here:
}//GEN-LAST:event_jLabelLogOutMouseClicked

private void jLabelLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogOutMouseEntered
    setLinkEntered(jLabelLogOut, linkHeaderColor);// TODO add your handling code here:
}//GEN-LAST:event_jLabelLogOutMouseEntered

private void jLabelLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogOutMouseExited
    setLinkExited(jLabelLogOut, this.headersFontColor);// TODO add your handling code here:
}//GEN-LAST:event_jLabelLogOutMouseExited
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRateMovies;
    private javax.swing.JButton jButtonSettings;
    private javax.swing.JButton jButtonSystemManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelHello;
    private javax.swing.JLabel jLabelLogOut;
    private javax.swing.JLabel jLabelMovie1;
    private javax.swing.JLabel jLabelMovie10;
    private javax.swing.JLabel jLabelMovie2;
    private javax.swing.JLabel jLabelMovie3;
    private javax.swing.JLabel jLabelMovie4;
    private javax.swing.JLabel jLabelMovie5;
    private javax.swing.JLabel jLabelMovie6;
    private javax.swing.JLabel jLabelMovie7;
    private javax.swing.JLabel jLabelMovie8;
    private javax.swing.JLabel jLabelMovie9;
    private javax.swing.JLabel jLabelPermission3;
    private javax.swing.JLabel jLabelPermissionMode;
    private javax.swing.JLabel jLabelPicture1;
    private javax.swing.JLabel jLabelPicture10;
    private javax.swing.JLabel jLabelPicture2;
    private javax.swing.JLabel jLabelPicture3;
    private javax.swing.JLabel jLabelPicture4;
    private javax.swing.JLabel jLabelPicture5;
    private javax.swing.JLabel jLabelPicture6;
    private javax.swing.JLabel jLabelPicture7;
    private javax.swing.JLabel jLabelPicture8;
    private javax.swing.JLabel jLabelPicture9;
    private javax.swing.JLabel jLabelRate1;
    private javax.swing.JLabel jLabelRate10;
    private javax.swing.JLabel jLabelRate2;
    private javax.swing.JLabel jLabelRate3;
    private javax.swing.JLabel jLabelRate4;
    private javax.swing.JLabel jLabelRate5;
    private javax.swing.JLabel jLabelRate6;
    private javax.swing.JLabel jLabelRate7;
    private javax.swing.JLabel jLabelRate8;
    private javax.swing.JLabel jLabelRate9;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
    //private Color backgroundColor = Color.DARK_GRAY;
    //private Color headerColor = new Color(255,51,51);
    //private Color regularFontColor = Color.LIGHT_GRAY;
    //private Color headersFontColor = Color.WHITE;

    public javax.swing.JPanel getJPanel1() {
        return jPanel1;
    }

    public javax.swing.JPanel getJPanel2() {
        return jPanel2;
    }

    public javax.swing.JPanel getJPanel4() {
        return jPanel4;
    }
    
}
