package gui;

public class RateMovies extends GeneralJFrame1 {
    
    /** Creates new form NewJFrame1 */
    public RateMovies() {
        setFrameAtCenter(getWidth(), getHeight());
	initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelRateMoviesTitle = new javax.swing.JLabel();
        jLabelMovieName = new javax.swing.JLabel();
        jButtonNextStep = new javax.swing.JButton();
        jComboBoxRate1 = new javax.swing.JComboBox();
        jLabelMovieName1 = new javax.swing.JLabel();
        jLabelMovieName2 = new javax.swing.JLabel();
        jLabelMovie1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelDirector1 = new javax.swing.JLabel();
        jLabelPicture1 = new javax.swing.JLabel();
        jLabelMovie2 = new javax.swing.JLabel();
        jLabelDirector2 = new javax.swing.JLabel();
        jComboBoxRate2 = new javax.swing.JComboBox();
        jLabelPicture2 = new javax.swing.JLabel();
        jLabelMovie3 = new javax.swing.JLabel();
        jLabelDirector3 = new javax.swing.JLabel();
        jComboBoxRate3 = new javax.swing.JComboBox();
        jLabelPicture3 = new javax.swing.JLabel();
        jLabelMovie4 = new javax.swing.JLabel();
        jLabelDirector4 = new javax.swing.JLabel();
        jComboBoxRate4 = new javax.swing.JComboBox();
        jLabelPicture4 = new javax.swing.JLabel();
        jLabelMovie5 = new javax.swing.JLabel();
        jLabelDirector5 = new javax.swing.JLabel();
        jComboBoxRate5 = new javax.swing.JComboBox();
        jLabelPicture5 = new javax.swing.JLabel();
        jLabelMovie6 = new javax.swing.JLabel();
        jLabelDirector6 = new javax.swing.JLabel();
        jComboBoxRate6 = new javax.swing.JComboBox();
        jLabelPicture6 = new javax.swing.JLabel();
        jLabelMovie7 = new javax.swing.JLabel();
        jLabelDirector7 = new javax.swing.JLabel();
        jComboBoxRate7 = new javax.swing.JComboBox();
        jLabelPicture7 = new javax.swing.JLabel();
        jButtonPreviousStep = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(GeneralJFrame1.backgroundColor);

        jPanel2.setBackground(backgroundColor);
        jPanel2.setForeground(new java.awt.Color(212, 208, 200));

        jPanel1.setBackground(backgroundColor);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setForeground(headersFontColor);

        jLabelRateMoviesTitle.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabelRateMoviesTitle.setForeground(headerColor);
        jLabelRateMoviesTitle.setText("Rate Movies");

        jLabelMovieName.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelMovieName.setForeground(headersFontColor);
        jLabelMovieName.setText("Movie's Name");

        jButtonNextStep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AT_next.gif"))); // NOI18N
        jButtonNextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextStepActionPerformed(evt);
            }
        });

        jComboBoxRate1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jLabelMovieName1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelMovieName1.setForeground(headersFontColor);
        jLabelMovieName1.setText("Director's Name");

        jLabelMovieName2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelMovieName2.setForeground(headersFontColor);
        jLabelMovieName2.setText("Rate");

        jLabelMovie1.setForeground(regularFontColor);
        jLabelMovie1.setText("Shrek1");

        jLabelDirector1.setForeground(regularFontColor);
        jLabelDirector1.setText("Mel Gibson");

        jLabelPicture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelMovie2.setForeground(regularFontColor);
        jLabelMovie2.setText("Shrek1");

        jLabelDirector2.setForeground(regularFontColor);
        jLabelDirector2.setText("Mel Gibson");

        jComboBoxRate2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jLabelPicture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelMovie3.setForeground(regularFontColor);
        jLabelMovie3.setText("Shrek1");

        jLabelDirector3.setForeground(regularFontColor);
        jLabelDirector3.setText("Mel Gibson");

        jComboBoxRate3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jLabelPicture3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelMovie4.setForeground(regularFontColor);
        jLabelMovie4.setText("Shrek1");

        jLabelDirector4.setForeground(regularFontColor);
        jLabelDirector4.setText("Mel Gibson");

        jComboBoxRate4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jLabelPicture4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelMovie5.setForeground(regularFontColor);
        jLabelMovie5.setText("Shrek1");

        jLabelDirector5.setForeground(regularFontColor);
        jLabelDirector5.setText("Mel Gibson");

        jComboBoxRate5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jLabelPicture5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelMovie6.setForeground(regularFontColor);
        jLabelMovie6.setText("Shrek1");

        jLabelDirector6.setForeground(regularFontColor);
        jLabelDirector6.setText("Mel Gibson");

        jComboBoxRate6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jLabelPicture6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jLabelMovie7.setForeground(regularFontColor);
        jLabelMovie7.setText("Shrek1");

        jLabelDirector7.setForeground(regularFontColor);
        jLabelDirector7.setText("Mel Gibson");

        jComboBoxRate7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jLabelPicture7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetNachleVerySmall.JPG"))); // NOI18N

        jButtonPreviousStep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AT_back.gif"))); // NOI18N
        jButtonPreviousStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousStepActionPerformed(evt);
            }
        });

        jButton1.setText("finish");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelRateMoviesTitle)
                .addContainerGap(412, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMovieName)
                .addGap(68, 68, 68)
                .addComponent(jLabelMovieName1)
                .addGap(80, 80, 80)
                .addComponent(jLabelMovieName2)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelMovie7)
                        .addGap(101, 101, 101)
                        .addComponent(jLabelDirector7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(jComboBoxRate7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabelPicture7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelMovie6)
                        .addGap(101, 101, 101)
                        .addComponent(jLabelDirector6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(jComboBoxRate6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabelPicture6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelMovie5)
                        .addGap(101, 101, 101)
                        .addComponent(jLabelDirector5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(jComboBoxRate5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabelPicture5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelMovie4)
                        .addGap(101, 101, 101)
                        .addComponent(jLabelDirector4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(jComboBoxRate4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabelPicture4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelMovie3)
                        .addGap(101, 101, 101)
                        .addComponent(jLabelDirector3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(jComboBoxRate3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabelPicture3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelMovie2)
                        .addGap(101, 101, 101)
                        .addComponent(jLabelDirector2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(jComboBoxRate2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabelPicture2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelMovie1)
                        .addGap(101, 101, 101)
                        .addComponent(jLabelDirector1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(jComboBoxRate1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabelPicture1)))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPreviousStep)
                .addGap(122, 122, 122)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jButtonNextStep, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRateMoviesTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMovieName1)
                    .addComponent(jLabelMovieName)
                    .addComponent(jLabelMovieName2))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelDirector1)
                                    .addComponent(jComboBoxRate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMovie1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPicture1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelDirector2)
                                    .addComponent(jComboBoxRate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMovie2)))
                            .addComponent(jLabelPicture2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelDirector3)
                                    .addComponent(jComboBoxRate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMovie3)))
                            .addComponent(jLabelPicture3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelDirector4)
                                    .addComponent(jComboBoxRate4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMovie4)))
                            .addComponent(jLabelPicture4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelDirector5)
                                    .addComponent(jComboBoxRate5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMovie5)))
                            .addComponent(jLabelPicture5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelDirector6)
                                    .addComponent(jComboBoxRate6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMovie6)))
                            .addComponent(jLabelPicture6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelDirector7)
                                    .addComponent(jComboBoxRate7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMovie7)))
                            .addComponent(jLabelPicture7))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNextStep)
                            .addComponent(jButtonPreviousStep))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(42, 42, 42))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonNextStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextStepActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButtonNextStepActionPerformed

private void jButtonPreviousStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousStepActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButtonPreviousStepActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    new MainFrame().setVisible(true);
}//GEN-LAST:event_jButton1ActionPerformed
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonNextStep;
    private javax.swing.JButton jButtonPreviousStep;
    private javax.swing.JComboBox jComboBoxRate1;
    private javax.swing.JComboBox jComboBoxRate2;
    private javax.swing.JComboBox jComboBoxRate3;
    private javax.swing.JComboBox jComboBoxRate4;
    private javax.swing.JComboBox jComboBoxRate5;
    private javax.swing.JComboBox jComboBoxRate6;
    private javax.swing.JComboBox jComboBoxRate7;
    private javax.swing.JLabel jLabelDirector1;
    private javax.swing.JLabel jLabelDirector2;
    private javax.swing.JLabel jLabelDirector3;
    private javax.swing.JLabel jLabelDirector4;
    private javax.swing.JLabel jLabelDirector5;
    private javax.swing.JLabel jLabelDirector6;
    private javax.swing.JLabel jLabelDirector7;
    private javax.swing.JLabel jLabelMovie1;
    private javax.swing.JLabel jLabelMovie2;
    private javax.swing.JLabel jLabelMovie3;
    private javax.swing.JLabel jLabelMovie4;
    private javax.swing.JLabel jLabelMovie5;
    private javax.swing.JLabel jLabelMovie6;
    private javax.swing.JLabel jLabelMovie7;
    private javax.swing.JLabel jLabelMovieName;
    private javax.swing.JLabel jLabelMovieName1;
    private javax.swing.JLabel jLabelMovieName2;
    private javax.swing.JLabel jLabelPicture1;
    private javax.swing.JLabel jLabelPicture2;
    private javax.swing.JLabel jLabelPicture3;
    private javax.swing.JLabel jLabelPicture4;
    private javax.swing.JLabel jLabelPicture5;
    private javax.swing.JLabel jLabelPicture6;
    private javax.swing.JLabel jLabelPicture7;
    private javax.swing.JLabel jLabelRateMoviesTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    
}
