/*
 * MovieDetails.java
 *
 * Created on 27 ספטמבר 2008, 12:23
 */

package gui;

import domain.Movie;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author  shaigi
 */
public class MovieDetails extends javax.swing.JFrame {

    private Movie _movie;
    private JFrame _parent;
    
    /** Creates new form MovieDetails */
    public MovieDetails(JFrame parent, Movie movie) {
        this._parent = parent;
        this._movie = movie;
        initComponents();
        setMoviesDetails();
    }
    
    @Override
    public void setVisible(boolean b){
        GeneralJFrame.setFrameAtCenter(this);
        super.setVisible(b);
    }
    
    private void setMoviesDetails() {
        this.jLabelID1.setText(""+_movie.get_id());
        this.jLabelID1.setToolTipText(""+_movie.get_id());
        this.jLabelName1.setText(_movie.get_name());
        this.jLabelName1.setToolTipText(_movie.get_name());
        this.jLabelDirector1.setText(_movie.get_director());
        this.jLabelDirector1.setToolTipText(_movie.get_director());
        this.jLabelCategory1.setText(_movie.get_category());
        this.jLabelCategory1.setToolTipText(_movie.get_category());
        try {
            this.jLabelActor1.setText(_movie.get_actors().elementAt(0));
            this.jLabelActor1.setToolTipText(_movie.get_actors().elementAt(0));
            this.jLabelActor2.setText(_movie.get_actors().elementAt(1));
            this.jLabelActor2.setToolTipText(_movie.get_actors().elementAt(1));
            this.jLabelActor3.setText(_movie.get_actors().elementAt(2));
            this.jLabelActor3.setToolTipText(_movie.get_actors().elementAt(2));
        } catch (Exception e) {
        }
        this.jLabelCountry1.setText(_movie.get_country());
        this.jLabelCountry1.setToolTipText(_movie.get_country());
        this.jLabelYear.setText(""+_movie.get_year());
        this.jLabelYear.setToolTipText(""+_movie.get_year());
        this.jLabelDuration1.setText(""+_movie.get_duration());
        this.jLabelDuration1.setToolTipText(""+_movie.get_duration());
        try {
            this.jLabelPicture.setIcon(new ImageIcon(getClass().getResource("/Images/" + _movie.get_name() + "_big.jpg")));
        } catch (Exception e) {
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelAddMovie = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelCountry = new javax.swing.JLabel();
        jLabelYear = new javax.swing.JLabel();
        jLabelActors = new javax.swing.JLabel();
        jLabelCategory = new javax.swing.JLabel();
        jLabelDirector = new javax.swing.JLabel();
        jLabelDuration = new javax.swing.JLabel();
        jButtonExitNoSaving = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelID1 = new javax.swing.JLabel();
        jLabelName1 = new javax.swing.JLabel();
        jLabelDirector1 = new javax.swing.JLabel();
        jLabelCategory1 = new javax.swing.JLabel();
        jLabelActor1 = new javax.swing.JLabel();
        jLabelYear1 = new javax.swing.JLabel();
        jLabelCountry1 = new javax.swing.JLabel();
        jLabelDuration1 = new javax.swing.JLabel();
        jLabelPicture = new javax.swing.JLabel();
        jLabelActor2 = new javax.swing.JLabel();
        jLabelActor3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Movie Details");

        jPanel2.setBackground(GeneralJFrame.backgroundColor);
        jPanel2.setForeground(new java.awt.Color(212, 208, 200));

        jPanel1.setBackground(GeneralJFrame.backgroundColor);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelAddMovie.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabelAddMovie.setForeground(GeneralJFrame.headerColor);
        jLabelAddMovie.setText("Movie Details");

        jLabelID.setText("ID:");

        jLabelName.setForeground(GeneralJFrame.regularFontColor);
        jLabelName.setText("Name:");

        jLabelCountry.setForeground(GeneralJFrame.regularFontColor);
        jLabelCountry.setText("Country:");

        jLabelYear.setForeground(GeneralJFrame.regularFontColor);
        jLabelYear.setText("Year:");

        jLabelActors.setForeground(GeneralJFrame.regularFontColor);
        jLabelActors.setText("Actors:");

        jLabelCategory.setForeground(GeneralJFrame.regularFontColor);
        jLabelCategory.setText("Category:");

        jLabelDirector.setForeground(GeneralJFrame.regularFontColor);
        jLabelDirector.setText("Director:");

        jLabelDuration.setForeground(GeneralJFrame.regularFontColor);
        jLabelDuration.setText("Duration:");

        jButtonExitNoSaving.setText("Exit");
        jButtonExitNoSaving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitNoSavingActionPerformed(evt);
            }
        });

        jLabel1.setText("(in minutes)");

        jLabelID1.setText("ID");

        jLabelName1.setForeground(GeneralJFrame.regularFontColor);
        jLabelName1.setText("Name");

        jLabelDirector1.setForeground(GeneralJFrame.regularFontColor);
        jLabelDirector1.setText("Director");

        jLabelCategory1.setForeground(GeneralJFrame.regularFontColor);
        jLabelCategory1.setText("Category");

        jLabelActor1.setForeground(GeneralJFrame.regularFontColor);
        jLabelActor1.setText("   ");

        jLabelYear1.setForeground(GeneralJFrame.regularFontColor);
        jLabelYear1.setText("Year");

        jLabelCountry1.setForeground(GeneralJFrame.regularFontColor);
        jLabelCountry1.setText("Country");

        jLabelDuration1.setForeground(GeneralJFrame.regularFontColor);
        jLabelDuration1.setText("Duration");

        jLabelPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sin City_big.jpg"))); // NOI18N

        jLabelActor2.setForeground(GeneralJFrame.regularFontColor);
        jLabelActor2.setText("    ");

        jLabelActor3.setForeground(GeneralJFrame.regularFontColor);
        jLabelActor3.setText("    ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelAddMovie))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelID)
                            .addComponent(jLabelName)
                            .addComponent(jLabelCategory)
                            .addComponent(jLabelActors)
                            .addComponent(jLabelDirector)
                            .addComponent(jLabelYear)
                            .addComponent(jLabelCountry)
                            .addComponent(jLabelDuration))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDuration1)
                            .addComponent(jLabelCountry1)
                            .addComponent(jLabelYear1)
                            .addComponent(jLabelDirector1)
                            .addComponent(jLabelName1)
                            .addComponent(jLabelID1)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelActor3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                .addComponent(jLabelCategory1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                .addComponent(jLabelActor2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                            .addComponent(jLabelActor1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonExitNoSaving)))
                .addGap(55, 55, 55)
                .addComponent(jLabelPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPicture)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelAddMovie)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDirector)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCategory)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelActors)
                                .addGap(46, 46, 46)
                                .addComponent(jLabelYear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCountry)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDuration))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelID1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelName1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDirector1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCategory1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelActor1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelActor2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelActor3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelYear1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCountry1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDuration1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)))
                        .addGap(24, 24, 24)
                        .addComponent(jButtonExitNoSaving)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonExitNoSavingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitNoSavingActionPerformed
    exit();
}//GEN-LAST:event_jButtonExitNoSavingActionPerformed

private void exit(){
    this._parent.setEnabled(true);
    this.setVisible(false);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExitNoSaving;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelActor1;
    private javax.swing.JLabel jLabelActor2;
    private javax.swing.JLabel jLabelActor3;
    private javax.swing.JLabel jLabelActors;
    private javax.swing.JLabel jLabelAddMovie;
    private javax.swing.JLabel jLabelCategory;
    private javax.swing.JLabel jLabelCategory1;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelCountry1;
    private javax.swing.JLabel jLabelDirector;
    private javax.swing.JLabel jLabelDirector1;
    private javax.swing.JLabel jLabelDuration;
    private javax.swing.JLabel jLabelDuration1;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelID1;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelName1;
    private javax.swing.JLabel jLabelPicture;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JLabel jLabelYear1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
